baseURL = 'https://fscotto.co/'
title = 'Fabio Scotto di Santolo'
languageCode = 'en-us'
copyright = '© 2026 Fabio Scotto di Santolo'
canonifyURLs = true
enableEmoji = true
enableRobotsTXT = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10


[module]
  [module.hugoVersion]
    extended = true
    min = '0.116.0'
  [[module.imports]]
    path = 'github.com/elecbrandy/freshpink'

[params]
description = 'Personal showcase for Fabio Scotto di Santolo'
primaryColor = '#fa8b84'
math = false
githubUsername = 'fscotto'
showGithubChart = true
showMainImage = false
copyright = 'Copyright © 2026 Fabio Scotto di Santolo'

[taxonomies]
tag = 'tags'
category = 'categories'
series = 'series'

[markup]
[markup.goldmark.renderer]
unsafe = true
